### ISSUE TITLE
Cant run run_training.py

### ISSUE THREAD

**Issue by josephldobson** [vye16/shape-of-motion#10]
(som) joe-ubuntu% python run_training.py data:iphone --data.data-dir '/home/joe/data/som/paper-windmill'                                            
╭─ Required options ───────────────────────────────╮
│ The following arguments are required: --work-dir │
│ ──────────────────────────────────────────────── │
│ Argument helptext:                               │
│     --work-dir STR                               │
│         (required)                               │
│             in run_training.py --help            │
│ ──────────────────────────────────────────────── │
│ For full helptext, run run_training.py --help

**Comment by aris-t** [comment]
this is how i formatted the command to at least get it working:
python run_training.py --work-dir ./outdir data:custom --data.seq-name untitled --data.root-dir ./preproc/indir/

with outdir:
./shape-of-motion/outdir

and indir:
./shape-of-motion/preproc/indir/

**Comment by josephldobson** [comment]
Thanks!
