### ISSUE TITLE
why align monodepth with metric depth instead of directly using metric depth

### ISSUE THREAD

**Issue by qian5683** [vye16/shape-of-motion#14]
Thanks for your good job. I want to know why align monodepth with metric depth instead of directly using metric depth?

**Comment by qianqianwang68** [comment]
Hi, we found that relative depth predictions tend to contain finer details compared to metric depth maps.

**Comment by Yuhuoo** [comment]
The purpose of the function is to convert the relative depth  to metric depth. So, are you actually using metric depth in your project?

![1729408770160](https://github.com/user-attachments/assets/a7e7218c-2ab6-4e46-ae3d-0ee3abc6b83e)
