### ISSUE TITLE
Questions about the monocular video dataset with the camera not moving

### ISSUE THREAD

**Issue by DingChunQ** [vye16/shape-of-motion#15]
Thank you for the Great work!

Your work seems to be able to handle monocular video with a fixed camera, but some previous work has performed poorly on this task.
I don't know much about nerf and 3dgs. Could you explain in an intuitive and profound way why it is more difficult to process static camera videos than videos with moving cameras for this task of obtaining dynamic 3d representations from monocular videos?
In addition, why can your work be applied to static camera videos (compared to previous work)? What modules or steps are mainly at work?

**Comment by hangg7** [comment]
Hi thanks for you nice words!

> Why it is more difficult to process static camera videos than videos with moving cameras for monocular DVS?
Intuitively, static camera doesn't give us stereo/MV signal to reason about 3D. Moving cameras instead come with this kind of cues. 

> Why can your work be applied to static camera videos?
Our work uses depth as input, which is very important for static camera cases.

Closing this! But please feel free to ask any follow up questions!

**Comment by DingChunQ** [comment]
https://github.com/user-attachments/assets/23e097b0-5ddc-46d6-b260-b59fd26be13a

Hi, this result is trained from a monocular video with static camera, where the obj is rotating. 
It can be seen that the rendering effect is quite good at the same viewing angle as the camera; but at other viewing angles, the rendering result is inaccurate. In other words, gs overfits the camera viewing angle at different times.
What might be the reason for this?
