### ISSUE TITLE
Small bugs in training bash

### ISSUE THREAD

**Issue by RuijieZhu94** [vye16/shape-of-motion#18]
It seems that there is no `--` before `data:iphone`.
The command should be
```
python run_training.py --work-dir <OUTPUT_DIR> --port <PORT> data:iphone --data.data-dir </path/to/paper-windmill/>
```

**Comment by lumoslxp** [comment]
我也遇到了相同的错误，
`python run_training.py  --work_dir lxp_output --port 8080 data:iphone --data.data-dir '/home/lxp/dataset/paper-windmill'`
会报错Unrecognized or misplaced options: --data:iphone --data.data-dir

**Comment by hangg7** [comment]
Hi guys! Thanks for reporting this error in our instruction. I have updated README.md accordingly.

Closing this!
