### ISSUE TITLE
About the demo scenes used in the teasar of project page.

### ISSUE THREAD

**Issue by zhaihongjia** [vye16/shape-of-motion#23]
![demo](https://github.com/user-attachments/assets/02649ecf-b40f-40b2-9d94-993651f5a2f2)
Hello, where can i download these two dataset?

**Comment by qianqianwang68** [comment]
Hi these two sequences are part of the DAVIS dataset which can be downloaded from https://davischallenge.org/davis2017/code.html#unsupervised. They are called swing and horsejump-high
