### ISSUE TITLE
Possible typo: track3d.invisibles instead of track3d.visibles in run_initial_optim()

### ISSUE THREAD

**Issue by heimrabe** [vye16/shape-of-motion#24]
Hi, thanks for the great work. I have seen the pull request suggesting that there might be a typo in the run_initial_optim() function in the flow3d/init_utils.py file.
As it says, there might be a typo and that:
`loss_2d = (
            masked_l1_loss(
                pred_2d,
                gt_2d,
                (tracks_3d.invisibles.float() * tracks_3d.confidences)[..., None],
                quantile=0.95,
            )
            / Ks[0, 0, 0]
        )`
should have tracks3d.visibles rather than track3d.invisibles. So I wanted to ask which of the 2 is the correct one, visibles or invisibles?

**Comment by qianqianwang68** [comment]
Hi invisible is the correct one. Loss for the visible points are already computed in the track 3d loss: https://github.com/vye16/shape-of-motion/blob/main/flow3d/init_utils.py#L320. The idea here is that for the invisible points, we found the 2D track prediction from TAPIR/BootsTAPIR is still pretty reasonable, but we don't have the corresponding depth. Therefore we only supervise the 3D tracks' 2D projection.

Feel free to reopen the issue if you have further questions.
