### ISSUE TITLE
May I ask what this parameter is used for --port <PORT>

### ISSUE THREAD

**Issue by lxin98** [vye16/shape-of-motion#3]
May I ask what this parameter is used for --port <PORT> in python run_training.py --work-dir <OUTPUT_DIR> --port <PORT> --data:iphone --data.data-dir </path/to/paper-windmill/>

**Comment by vye16** [comment]
If you want to visualize the training process, you can specify a port during training, which you can forward to your local machine. You can then view and interact with the training scene at localhost:<PORT>

**Comment by lxin98** [comment]
Thanks for making this code available!Thank you for your response
