### ISSUE TITLE
Initilization of static area

### ISSUE THREAD

**Issue by ZcsrenlongZ** [vye16/shape-of-motion#31]
Why use back-projected depth to initialize static area, not point cloud from colmap?

**Comment by hangg7** [comment]
We tried both during our experiments and find that although colmap works for wide baseline settings where you scan almost 360 of the scene, it doesn't work very well when the capture is most frontal, and will produce stretchy gaussians in bkgd. We decided to make backproj depth our default way to get a denser init.

**Comment by ZcsrenlongZ** [comment]
Thanks for your help!

**Comment by ZcsrenlongZ** [comment]
If it is possible to provide the code to intialize static area with colmap point cloud? Even unpacked?

**Comment by ZcsrenlongZ** [comment]
I have finished it,thanks!

**Comment by ZcsrenlongZ** [comment]
Sorry to bother you. I want to know why normalize the poses according to foreground?
