### ISSUE TITLE
Encounter error during preprocessing of DAVIS/schoolgirls scene

### ISSUE THREAD

**Issue by Yuhuoo** [vye16/shape-of-motion#54]
Hi, thanks for your nice work. When I preprocessed the scene of DAVIS/schoolgirls, I encountered an error. Here is the error log.

(som) ga@test-4U-GPU-Server:~/code/shape-of-motion/preproc$ python process_custom.py --img-dirs /home/ga/code/shape-of-motion/datasets/custom/images/schoolgirls/ --gpus 0 2

found 150 files in /home/ga/code/shape-of-motion/datasets/custom/unidepth_disp/schoolgirls, found /home/ga/code/shape-of-motion/datasets/custom/unidepth_intrins/schoolgirls.json, skipping
CUDA_VISIBLE_DEVICES=0 python compute_depth.py --img_dir /home/ga/code/shape-of-motion/datasets/custom/images/schoolgirls --out_raw_dir /home/ga/code/shape-of-motion/datasets/custom/depth_anything/schoolgirls --out_aligned_dir /home/ga/code/shape-of-motion/datasets/custom/aligned_depth_anything/schoolgirls --model depth-anything --metric_dir /home/ga/code/shape-of-motion/datasets/custom/unidepth_disp/schoolgirls
Raw depth-anything depth maps already computed for /home/ga/code/shape-of-motion/datasets/custom/images/schoolgirls
Aligning monodepth in /home/ga/code/shape-of-motion/datasets/custom/depth_anything/schoolgirls with metric depth in /home/ga/code/shape-of-motion/datasets/custom/unidepth_disp/schoolgirls
Founds 150 files in /home/ga/code/shape-of-motion/datasets/custom/aligned_depth_anything/schoolgirls, skipping
CUDA_VISIBLE_DEVICES=0 python recon_with_depth.py --img_dir /home/ga/code/shape-of-motion/datasets/custom/images/schoolgirls --calib /home/ga/code/shape-of-motion/datasets/custom/unidepth_intrins/schoolgirls.json --depth_dir /home/ga/code/shape-of-motion/datasets/custom/aligned_depth_anything/schoolgirls --out_path /home/ga/code/shape-of-motion/datasets/custom/droid_recon/schoolgirls
0it [00:00, ?it/s]checkpoints/droid.pth
/home/ga/software/anaconda3/envs/som/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
150it [00:03, 40.63it/s]
################################
Traceback (most recent call last):
  File "/data/Gaoao/code/shape-of-motion/preproc/recon_with_depth.py", line 265, in <module>
    traj_est = droid.terminate(image_stream(args.img_dir, args.calib, args.stride))
  File "/data/Gaoao/code/shape-of-motion/preproc/DROID-SLAM/droid_slam/droid.py", line 81, in terminate
    self.backend(7)
  File "/home/ga/software/anaconda3/envs/som/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/Gaoao/code/shape-of-motion/preproc/DROID-SLAM/droid_slam/droid_backend.py", line 34, in __call__
    graph.add_proximity_factors(rad=self.backend_radius, 
  File "/data/Gaoao/code/shape-of-motion/preproc/DROID-SLAM/droid_slam/factor_graph.py", line 374, in add_proximity_factors
    ii, jj = torch.as_tensor(es, device=self.device).unbind(dim=-1)
ValueError: not enough values to unpack (expected 2, got 0)

Can you help me?

**Comment by yingxuanyou** [comment]
I encounter the same problem, how do you solve it?

**Comment by yingxuanyou** [comment]
> I encounter the same problem, how do you solve it?

I referred to this (https://github.com/princeton-vl/DROID-SLAM/issues/115#issuecomment-2352400027) and solved the problem. Holp it can help you.

**Comment by YuyangYin** [comment]
thanks发件人: ***@***.*** ***@***.***> 代表 Yingxuan You ***@***.***>发送时间: 星期五, 十一月 15, 2024 6:10:06 上午收件人: vye16/shape-of-motion ***@***.***>抄送: YuyangYin ***@***.***>; Comment ***@***.***>主题: Re: [vye16/shape-of-motion] Encounter error during preprocessing of DAVIS/schoolgirls scene (Issue #54)

I encounter the same problem, how do you solve it?

I referred to this (princeton-vl/DROID-SLAM#115 (comment)) and solved the problem. Holp it can help you.
