### ISSUE TITLE
Unrecognized options when trying train on custom data

### ISSUE THREAD

**Issue by DevikalyanDas** [vye16/shape-of-motion#7]
Hello @vye16, thanks for your amazing work. I tried to run you code for custom data. I processed the data as per the provided preprocessed steps. When I am trying to run the code for training, I am getting this error 
![image](https://github.com/user-attachments/assets/68620e3d-f9b2-496e-94d3-d245c21835c0)

I think I am not able to pass the correct the arguments. Can you please help?

Thanks

**Comment by lzylucy** [comment]
python run_training.py --work-dir <YOUR_OUTPUT_DIR> data:custom --data.seq-name <YOUR_SEQ_NAME> --data.root-dir <YOUR_PROCESSED_DATA_DIR>
