### ISSUE TITLE
Rendering Quality is not good

### ISSUE THREAD

**Issue by DevikalyanDas** [vye16/shape-of-motion#8]
Hello @vye16 , thanks for your amazing work. I tried to run code following the steps (both for preprocessing and training) on a cat video from Banmo. I tried to obtain the rendering video using ''lemniscate'' trajectory but the quality is not good. Here is the video. I am not sure what is going wrong? 

https://github.com/user-attachments/assets/06d852a6-2efe-4666-b248-d4f2b0bac6ed

**Comment by vye16** [comment]
Hi, this can happen if the rendering trajectory is too far away from the training views, and depending on how the training cameras and depth maps look. A better way to debug is to run the rendering script 
```python run_rendering.py --work-dir [WORK_DIR]``` 
to interactively view the trained model.

**Comment by CTouch** [comment]
@DevikalyanDas Did you get the video using `run_video.py`? I am trying to try  `som` on `nvidia-long` dataset. I have already done the `preprocess` and `train`, got the `custom dataset` and `ckpt`. I am trying to get the rendering videos. Could you please tell me how did you made it?
Thank you!

**Comment by DevikalyanDas** [comment]
@CTouch Yes I got the video using ``run_video.py``. As far as I remember, the script was already working except for some changes in the dataloader for running the custom videos and you also have to provide the type of trajectory that you want to perform during rendering as commandline arguments. I think if the script is working for training the custom videos then it will work for rendering also.

**Comment by CTouch** [comment]
> @CTouch Yes I got the video using `run_video.py`. As far as I remember, the script was already working except for some changes in the dataloader for running the custom videos and you also have to provide the type of trajectory that you want to perform during rendering as commandline arguments. I think if the script is working for training the custom videos then it will work for rendering also.

Got it! Thank you!
